### ISSUE TITLE
DNFの理由をスクランブルし直して確認してから選びたい

### ISSUE THREAD

**Issue by sakabar** [shintaro-hirose/hcon_client#106]
タイマーモードでの話です。

試技が終わった直後にDNFを選ぶと失敗した原因の選択肢が出ますが、そのスクランブルでもう一度崩してみないと原因が特定できないことがあります。
しかし、現在はn試技目のDNF理由を選ぼうとしている時には既に(n+1)試技目のスクランブルが表示されているため、確認ができません。

(もしかするとタイムを手入力する場合は問題ないかもしれません)

【提案】
* (誤解が発生しないように注意しつつ) 前の試技のスクランブルを表示できるようにする
* 3試技終わった時にスクランブルを確認しつつDNF理由を選び直せるようにする

**Comment by shintaro-hirose** [comment]
@sakabar 提案ありがとうございます
・終わった試技のスクランブルを灰色で表示する
・結果確認画面で全スクランブルを表示させる
以上の修正を加えます

**Comment by sakabar** [comment]
確認しました、ご対応ありがとうございます。
