### ISSUE TITLE
結果を確定する際にOK/+2/DNFの入力を必須にしてほしい

### ISSUE THREAD

**Issue by sakabar** [shintaro-hirose/hcon_client#124]
コンテストの結果を確定する直前の画面で、現在はOK/+2/DNFの入力が必須ではないため、DNFや+2をうっかり入力し忘れた場合に気づかずに確定してしまう可能性があります。

そこで、確定ボタンを押した際にそれぞれの試技でOK/+2/DNFのいずれかが選択されているかをチェックするとよいと考えました。

**Comment by shintaro-hirose** [comment]
@sakabar  提案ありがとうございます！
試技のステータスが入力されていない場合、エラーを表示するようにします！

**Comment by shintaro-hirose** [comment]
修正しました
