### ISSUE TITLE
今日のコンテストに参加済みのとき、トップページから今日の暫定ランキングに飛べるようにしてほしい

### ISSUE THREAD

**Issue by sakabar** [shintaro-hirose/hcon_client#135]
今日のコンテストの暫定結果を確認するのに2ステップ必要でちょっと面倒なので、今日のコンテストに参加済みのとき、トップページから今日の暫定ランキングに飛べるようにしてほしいです。

試技が終わった後、今はトップページには緑文字の「参加済み」が表示されるだけですが、これを「参加済み: 暫定ランキングを確認」のリンクにするイメージです。

**Comment by shintaro-hirose** [comment]
@sakabar たしかに面倒ですね。直します。

**Comment by shintaro-hirose** [comment]
直しました。
