### ISSUE TITLE
マイページに遷移しても他の人のタイムが表示されたままになる

### ISSUE THREAD

**Issue by sakabar** [shintaro-hirose/hcon_client#48]
再現方法

1. 誰か他の人(Aさんとする)のユーザー情報を見る
2. 「マイページ」タブをクリックする

左側のアイコンは自分のアイコンになるのですが、右側のタイムなどの情報はAさんの情報が表示されたままになります。

**Comment by shintaro-hirose** [comment]
@sakabar 
報告ありがとうございます。再現を確認しました。

マイページのマウント時にユーザのデータをfetchしていないことが原因と思われます。
修正します。
