### ISSUE TITLE
Twitterアカウント名のバリデーション

### ISSUE THREAD

**Issue by sakabar** [shintaro-hirose/hcon_client#54]
プロフィールとして登録するTwitterアカウントですが、[0-9a-zA-Z]のバリデーションがついていないので以下のようなリンクも指定することができてしまいます。
`intent/tweet?text=Hcon%E3%81%9F%E3%81%AE%E3%81%97%E3%81%84`

このリンクは新規ツイート画面にいくだけなので害はないですが、もしかすると「特定のツイートをRTする」というような悪意のあるリンクが作れてしまう可能性があるため、バリデーションをつけたほうがよいと思います。

**Comment by shintaro-hirose** [comment]
@sakabar 報告ありがとうございます！

現状、
twitterアカウント名のバリデーションは何もつけていない状態です
確かに、予期せぬ入力を防ぐためにバリデーションをつける必要がありそうです

twitter名の安全なバリデーションについて勉強して対応します
