### ISSUE TITLE
今日のコンテストの結果が個人のプロフィールからわかってしまう

### ISSUE THREAD

**Issue by sakabar** [shintaro-hirose/hcon_client#69]
今日のコンテストの結果は明日になるまでは秘密というスタンスだと思うのですが、実際には以下ようにタイムの情報を得ることができてしまいます。

* プロフィールページの参加履歴
* トップページのランク・best

いくつか対応方法はありそうですが、例えば以下のような対応が考えられます。

* ランキングの反映を0:00にする
* 他の人のプロフィールを見たときには、昨日までの結果しかわからない
  * 本人は、当日のうちに最新の結果を見ることができる

**Comment by shintaro-hirose** [comment]
@sakabar 報告ありがとうございます

これについてですが、「今日の結果は今日のうちに見れても構わない」
というスタンスです。

これは
・順位によってポイントが変動しない
・日々のコンテストは対人戦というより自分の記録付けのために使って欲しい
という考えの元です

現状、結果画面では今日の結果を確認できないのでそこは統一性がなく、
どうするかは考え中です

**Comment by sakabar** [comment]
@shintaro-hirose なるほどです、スタンスについては分かりました。
hiroseさんも言っている通り、スタンスに統一性があったほうがよいと思います。

**Comment by sakabar** [comment]
https://github.com/shintaro-hirose/hcon_client/issues/71#issuecomment-591397845
> 今日の結果画面を有効にします！！！

このスタンスの下では、このissueは新しい機能には紐付かないのでクローズします。
