### ISSUE TITLE
試技の最後の確認画面のタイム表示

### ISSUE THREAD

**Issue by sakabar** [shintaro-hirose/hcon_client#70]
起こったこと
試技の結果が50秒、60秒、DNFの時、確認画面では60秒のタイムが太字で表示されました。

3つの結果を全て表示するか、bestのタイムを表示するほうが自然だと思います。

**Comment by shintaro-hirose** [comment]
@sakabar 報告ありがとうございます
これはタイム手入力での動作ですか？

**Comment by sakabar** [comment]
@shintaro-hirose 説明が不充分でしたね、手入力ではなくタイマーです。

**Comment by shintaro-hirose** [comment]
@sakabar ありがとうございます。確認します

**Comment by shintaro-hirose** [comment]
@sakabar 
こちら再現できませんでした
ブラウザ情報ください
![image](https://user-images.githubusercontent.com/48212107/75346842-e705ed80-58e2-11ea-89b3-9497ce04414f.png)
