### ISSUE TITLE
プロフィールから今日のコンテスト結果に遷移できそうでできず、ガッカリする

### ISSUE THREAD

**Issue by sakabar** [shintaro-hirose/hcon_client#71]
プロフィールの「コンテスト参加履歴」で今日の日付にカーソルを合わせて「コンテストのページへ行く」リンクを叩くとトップページに遷移します。

コンテスト結果ページは翌日になるまで見ることができない作りなので理解はできるのですが、表示されている説明と挙動が一致していないので気になります。

【提案】
* 「コンテスト参加履歴」で、今日の日付はリンクそのものをdisableし、クリックできないようにする
* 今日の結果にカーソルを合わせた時
  * ポップアップが表示されないようにする
  * ポップアップの文言を変える (例: コンテスト結果は明日以降に確認できます)

**Comment by shintaro-hirose** [comment]
今日の結果画面を有効にします！！！
リアルタイムで見てもらえるというスタンスにします

**Comment by sakabar** [comment]
@shintaro-hirose 承知しました!
