### ISSUE TITLE
Twitterアカウント名のバリデーションに引っかかっている場合は保存ボタンを押せなくする

### ISSUE THREAD

**Issue by sakabar** [shintaro-hirose/hcon_client#72]
https://github.com/shintaro-hirose/hcon_client/pull/64 でバリデーションをかけていただきましたが、保存ボタンと連動していないため、「保存ボタンを押すことはできるが表示が変わらず、不思議に思ってもう一度編集した時になってようやく赤い文字の警告が見える」という状態になっています。

そこで、保存ボタンを押した時にバリデーションチェックがかかるようにし、引っかかった場合はモーダルを閉じないようにしたほうがよいと思います。

**Comment by shintaro-hirose** [comment]
@sakabar 報告ありがとうございます
エラースナックバー追加しましたが、わかりにくいのでとりやめて
保存されなかったときはモーダル閉じないようにします
